[package]
name = "cancellation-patterns"
version = "0.1.0"
edition = "2021"
authors = ["milosgajdos <milosthegajdos@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
tokio-util = { version = "0.7.10" }
